config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :microposts
    resources :comments
  end

  resources :users do
    resources :microposts do
      resources :comments
    end
  end

  resources :users do
    resources :microposts, only: [:new, :create]
  end

  resources :microposts do
    resources :comments
  end
  resources :users
  resources :microposts
  resources :comments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :micropost
  belongs_to :user
  validates :commenter, presence: true
  validates :body, length: { maximum: 140 }, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
    if params.key?(:user_id)
      @user = User.find(params[:user_id])
    end
    if params.key?(:micropost_id)
      @micropost = Micropost.find(params[:micropost_id])
    end
    @comment = Comment.find(params[:id])
  end

  # GET /comments/new
  def new
    if params.key?(:user_id)
      @user = User.find(params[:user_id])
    end
    @micropost = Micropost.find(params[:micropost_id])
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
    if params.key?(:user_id)
      @user = User.find(params[:user_id])
    end
    @micropost = Micropost.find(params[:micropost_id])
  end

  # POST /comments or /comments.json
  def create
    if params.key?(:user_id)
      # if the micropost doesn't exist, return an error
      @micropost = Micropost.find(params[:micropost_id])
      @user = User.find(params[:user_id])
      # @comment = @micropost.comments.build(comment_params)
      @comment = Comment.new(comment_params)
      respond_to do |format|
        if @comment.save
          format.html { redirect_to user_micropost_comment_url(@user, @micropost, @comment), notice: "Comment was successfully created." }
          format.json { render :show, status: :created, location: @comment }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    else
      @micropost = Micropost.find(params[:micropost_id])
      @comment = Comment.new(comment_params)

      respond_to do |format|
        if @comment.save
          # format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
          format.html { redirect_to micropost_comment_url(@micropost, @comment), notice: "Comment was successfully created." }
          format.json { render :show, status: :created, location: @comment }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:commenter, :body, :micropost_id, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= comment.body %>
  </p>

  <p>
    <strong>Micropost Id:</strong>
    <%= comment.micropost_id %>
  </p>

  <p>
    <strong>User Id:</strong>
    <%= comment.user_id %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: [@user, @micropost, comment], local: true) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  
  <div>
    <%= form.hidden_field :micropost_id, value: @micropost.id %>
  </div>
  
  <div>
    <% if defined?(@user) %>
      <%= form.hidden_field :user_id, value: @user.id %>
      <% puts "User ID: #{@user.id}" %>
    <% else %>
      <%= form.label :user_id, style: "display: block" %>
      <%= form.number_field :user_id %>
    <% end %>
  </div>
  
  <div>
    <%= form.label :commenter, style: "display: block" %>
    <%= form.text_field :commenter %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>


<div>
  <%= link_to "Back to this micropost", micropost_path(@micropost) %>
</div>

<br>

<div>
  <%= link_to "Back to all comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<h2> Comment Information </h2>
<%= render @comment %>

<h2>Options</h2>
<div>
  <% if defined?(@user) and @user.id == @comment.user_id %>
    <%= button_to "Destroy this comment", @comment, method: :delete %>
    <% if defined?(@micropost) %>
      <%= link_to "Edit this comment", edit_user_micropost_comment_path(@user, @micropost, @comment) %>
    <% end %>
  <% end %>
</div>

<br>

<div>
  <% if defined?(@user) and @user.id == @comment.user_id %>
    <%= link_to "Back to the user", user_path(@user) %>
    <br>
    <% if defined?(@micropost) %>
      <%= link_to "Back to this micropost", user_micropost_path(@user, @micropost) %>
    <% end %>
  <% else %>
    <% if defined?(@micropost) %>
      <%= link_to "Back to this micropost", micropost_path(@micropost) %>
    <% end %>
  <% end %>
</div>

<div>
  <%= link_to "Back to all comments", comments_path %>
</div>