config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :microposts
    resources :comments
  end

  resources :users do
    resources :microposts do
      resources :comments
    end
  end

  resources :users do
    resources :microposts, only: [:new, :create]
  end

  resources :microposts do
    resources :comments
  end
  resources :users
  resources :microposts
  resources :comments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/micropost.rb
class Micropost < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    validates :title, length: { maximum: 140 }, presence: true
    validates :content, length: { maximum: 140 }, presence: true
    validates :user_id, presence: true
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: %i[ show edit update destroy ]

  # GET /microposts or /microposts.json
  def index
    if params.key?(:user_id)
      @user = User.find(params[:user_id])
    end
    @microposts = Micropost.all
  end

  # GET /microposts/1 or /microposts/1.json
  def show
    if params.key?(:user_id)
      @user = User.find(params[:user_id])
    end
    @micropost = Micropost.find(params[:id])
    @comment = @micropost.comments
  end

  # GET /microposts/new
  def new
    if params.key?(:user_id)
      @user = User.find(params[:user_id])
    end
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
    if params.key?(:user_id)
      @user = User.find(params[:user_id])
    end
  end

  # POST /microposts or /microposts.json
  def create
    if params.key?(:user_id)
      @user = User.find(params[:user_id])
      @micropost = @user.microposts.build(micropost_params)

      respond_to do |format|
        if @micropost.save
          format.html { redirect_to user_micropost_url(@user, @micropost), notice: "Micropost was successfully created." }
          format.json { render :show, status: :created, location: @micropost }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @micropost.errors, status: :unprocessable_entity }
        end
      end
    else
      @micropost = Micropost.new(micropost_params)
      respond_to do |format|
        if @micropost.save
          format.html { redirect_to micropost_url(@micropost), notice: "Micropost was successfully created." }
          format.json { render :show, status: :created, location: @micropost }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @micropost.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /microposts/1 or /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        if params.key?(:user_id)
          @user = User.find(params[:user_id])
          format.html { redirect_to user_micropost_url(@user, @micropost), notice: "Micropost was successfully updated." }
        else
          format.html { redirect_to micropost_url(@micropost), notice: "Micropost was successfully updated." }
        format.json { render :show, status: :ok, location: @micropost }
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1 or /microposts/1.json
  def destroy
    @micropost.destroy!

    respond_to do |format|
      format.html { redirect_to microposts_url, notice: "Micropost was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def micropost_params
      params.require(:micropost).permit(:title, :content, :user_id)
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_with(model: [@user, @micropost], local: true) do |form| %>
  <% if micropost.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
        <% micropost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_area :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <% if !defined?(@user) %>
      <%= form.label :user_id, style: "display: block" %>
      <%= form.number_field :user_id %>
    <% else %>
      <%= form.hidden_field :user_id, value: @user.id %>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<div id="<%= dom_id micropost %>">
  <p>
    <strong>Title:</strong>
    <%= micropost.title %>
  </p>
  <p>
    <strong>Content:</strong>
    <%= micropost.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= micropost.user_id %>
  </p>

</div>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render "form", micropost: @micropost %>

<br>

<div>
  <%= link_to "Show this micropost", @micropost %> |
  <%= link_to "Back to microposts", microposts_path %>
</div>

app/views/microposts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Microposts</h1>

<div id="microposts">
  <% @microposts.each do |micropost| %>
    <%= render micropost %>
    <p>
    <% if defined?(@user) %>
      <%= link_to "Show this micropost", user_micropost_path(@user, micropost) %>
    <% else %>
      <%= link_to "Show this micropost", micropost %>
    <% end %>
    </p>
  <% end %>
</div>

<h2> Make New Micropost </h2>
<% if defined?(@user) %>
  <%= link_to "New micropost", new_user_micropost_path(@user) %>
<% else %>
  <%= link_to "New micropost", new_micropost_path %>
<% end %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render "form", micropost: @micropost %>

<br>

<div>
  <%= link_to "Back to all microposts", microposts_path %>
</div>

<br>

<div>
  <% if defined?(@user) %>
    <%= link_to "Back to this user", user_path(@user) %>
  <% end %>
</div>

app/views/microposts/show.html.erb
<p style="color: green"><%= notice %></p>


<h2>Post Information</h2>
<%= render @micropost %>

<h2>Options</h2>
<div>
  <% if defined?(@user) and @user.id == @micropost.user_id%>
    <%= link_to "Edit this micropost", edit_user_micropost_path(@user, @micropost) %>  
    <br>
    <br>
    <%= button_to "Destroy this micropost", @micropost, method: :delete %>
    <br>
    <%= link_to "Back to the user", user_path(@user) %>
      
  <% end %>
  <br>
  <%= link_to "Back to all microposts", microposts_path %> 
</div>

<h2>All Comments</h2>
<ul>
  <% @micropost.comments.each do |comment| %>
    <li>
      <p>
        <strong>Commenter:</strong>
        <%= comment.commenter %>
      </p>
      <p>
        <strong>Comment Body:</strong>
        <%= comment.body %>
      </p>
      <p>
        <!-- <%= link_to "Show this comment", micropost_comment_path(@micropost, comment) %> -->
        <!-- <%= link_to "Show this comment", comment %> -->


        <% if defined?(@user) %>
          <%= link_to "Show this comment", user_micropost_comment_path(@user, @micropost, comment) %>
        <% else %>
          <%= link_to "Show this comment", micropost_comment_path(@micropost, comment) %>
        <% end %>

      </p>
    </li>
  <% end %>
</ul>


<h2>Post Comments</h2>

<% if defined?(@user) %>
  <%= link_to "New Comment", new_user_micropost_comment_path(@user, @micropost) %>
<% else %>
  <%= link_to "New Comment", new_micropost_comment_path(@micropost) %>
<% end %>